sync:
  alipan_directory_name: "emby"
  dav_directory: "/mnt/user/downloads/CloudDrive"
  dav_source_directory: "/aliyun/emby"
  destination_directory: "/mnt/user/downloads/link/aliyun"
  emby_directory: "/data/aliyun"
  dav_url: "192.168.31.103:19798"
  straight_chain: true
